"""projects/episodes 的 Repository 与 Unit of Work 端口。"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from video_agent_api.domain.assets import Asset, AssetVersion
from video_agent_api.domain.entities import Episode, Project


class ProjectRepository(Protocol):
    async def get(self, project_id: str) -> Project | None: ...

    async def list(self) -> Sequence[Project]: ...

    async def add(self, project: Project) -> None: ...

    async def save(self, project: Project) -> None: ...


class EpisodeRepository(Protocol):
    async def get(self, episode_id: str) -> Episode | None: ...

    async def list_by_project(self, project_id: str) -> Sequence[Episode]: ...

    async def add(self, episode: Episode) -> None: ...

    async def save(self, episode: Episode) -> None: ...


class AssetRepository(Protocol):
    async def get(self, asset_id: str) -> Asset | None: ...

    async def list_by_project(self, project_id: str) -> Sequence[Asset]: ...

    async def add(self, asset: Asset) -> None: ...


class AssetVersionRepository(Protocol):
    async def get(self, version_id: str) -> AssetVersion | None: ...

    async def list_by_asset(self, asset_id: str) -> Sequence[AssetVersion]: ...

    async def next_version_number(self, asset_id: str) -> int: ...

    async def add(self, version: AssetVersion) -> None: ...


class ProjectsEpisodesUnitOfWork(Protocol):
    projects: ProjectRepository
    episodes: EpisodeRepository

    async def __aenter__(self) -> ProjectsEpisodesUnitOfWork: ...

    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class AssetsUnitOfWork(Protocol):
    projects: ProjectRepository
    assets: AssetRepository
    asset_versions: AssetVersionRepository

    async def __aenter__(self) -> AssetsUnitOfWork: ...

    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> ProjectsEpisodesUnitOfWork: ...


class AssetsUnitOfWorkFactory(Protocol):
    def __call__(self) -> AssetsUnitOfWork: ...
