CREATE TABLE video_workspace_menus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_id UUID REFERENCES video_workspace_menus(id) ON DELETE CASCADE,
    menu_key VARCHAR(80) NOT NULL,
    label VARCHAR(60) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    route_path VARCHAR(160),
    icon VARCHAR(40) NOT NULL DEFAULT '',
    menu_type VARCHAR(20) NOT NULL,
    module_key VARCHAR(80),
    agent_key VARCHAR(80),
    sort_order INT NOT NULL DEFAULT 0,
    is_enabled BOOLEAN NOT NULL DEFAULT false,
    is_visible BOOLEAN NOT NULL DEFAULT true,
    status VARCHAR(20) NOT NULL DEFAULT 'planned',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT video_workspace_menus_menu_key_unique UNIQUE(menu_key),
    CONSTRAINT video_workspace_menus_parent_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT video_workspace_menus_sort_order_check CHECK (sort_order >= 0),
    CONSTRAINT video_workspace_menus_type_check CHECK (menu_type IN ('section', 'page', 'group')),
    CONSTRAINT video_workspace_menus_status_check CHECK (status IN ('active', 'planned', 'disabled'))
);

COMMENT ON TABLE video_workspace_menus IS 'VEDIO-AGENT 视频工作台业务菜单配置，驱动 apps/video-agent 前端导航。';
COMMENT ON COLUMN video_workspace_menus.menu_key IS '稳定业务键，前后端以此识别菜单，不依赖 UUID。';
COMMENT ON COLUMN video_workspace_menus.parent_id IS '父菜单；为空表示一级业务菜单。';
COMMENT ON COLUMN video_workspace_menus.is_enabled IS '是否允许进入该菜单视图；计划态菜单可见但不可点击。';
COMMENT ON COLUMN video_workspace_menus.is_visible IS '是否返回给视频工作台前端。';

CREATE INDEX idx_video_workspace_menus_parent_sort
    ON video_workspace_menus(parent_id, sort_order, menu_key);
CREATE INDEX idx_video_workspace_menus_visible
    ON video_workspace_menus(is_visible)
    WHERE is_visible = true;
CREATE INDEX idx_video_workspace_menus_module
    ON video_workspace_menus(module_key)
    WHERE module_key IS NOT NULL;
CREATE INDEX idx_video_workspace_menus_agent
    ON video_workspace_menus(agent_key)
    WHERE agent_key IS NOT NULL;

CREATE TRIGGER trigger_video_workspace_menus_updated_at
    BEFORE UPDATE ON video_workspace_menus
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

INSERT INTO video_workspace_menus (
    id,
    parent_id,
    menu_key,
    label,
    description,
    route_path,
    icon,
    menu_type,
    module_key,
    agent_key,
    sort_order,
    is_enabled,
    is_visible,
    status,
    metadata
) VALUES
    (
        '10000000-0000-4000-8000-000000000001',
        NULL,
        'content-strategy',
        '内容策略',
        '选题池、热点趋势、账号定位、受众画像和策略建议。',
        '/strategy',
        'lightbulb',
        'section',
        'strategy',
        NULL,
        10,
        false,
        true,
        'planned',
        '{"phase":2}'::jsonb
    ),
    (
        '10000000-0000-4000-8000-000000000002',
        NULL,
        'script-creation',
        '脚本创作',
        '脚本生成、分镜确认、时间轴详情和状态流转。',
        '/scripts',
        'file-pen-line',
        'section',
        'script',
        NULL,
        20,
        true,
        true,
        'active',
        '{"phase":1}'::jsonb
    ),
    (
        '10000000-0000-4000-8000-000000000003',
        NULL,
        'material-management',
        '素材管理',
        '素材库、标签、语义检索、素材候选和素材清单确认。',
        '/materials',
        'folder-search',
        'section',
        'materials',
        NULL,
        30,
        false,
        true,
        'planned',
        '{"phase":3}'::jsonb
    ),
    (
        '10000000-0000-4000-8000-000000000004',
        NULL,
        'production',
        '作品生产',
        '模板选择、配音字幕、视频生成任务、成片预览和重生成。',
        '/production',
        'clapperboard',
        'section',
        'production',
        NULL,
        40,
        false,
        true,
        'planned',
        '{"phase":4}'::jsonb
    ),
    (
        '10000000-0000-4000-8000-000000000005',
        NULL,
        'publishing',
        '发布运营',
        '多平台账号、标题封面标签、发布排程、状态和失败重试。',
        '/publishing',
        'send',
        'section',
        'publishing',
        NULL,
        50,
        false,
        true,
        'planned',
        '{"phase":5}'::jsonb
    ),
    (
        '10000000-0000-4000-8000-000000000006',
        NULL,
        'analytics',
        '数据分析',
        '播放、完播、互动、转化、平台表现和内容表现分析。',
        '/analytics',
        'chart-no-axes-combined',
        'section',
        'analytics',
        NULL,
        60,
        false,
        true,
        'planned',
        '{"phase":6}'::jsonb
    ),
    (
        '10000000-0000-4000-8000-000000000007',
        NULL,
        'workflow-tasks',
        '工作流任务',
        'DAG 任务、Agent 执行步骤、失败重试、状态机和产物链路。',
        '/workflow-tasks',
        'workflow',
        'section',
        'workflow',
        NULL,
        70,
        false,
        true,
        'planned',
        '{"phase":7}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000001',
        '10000000-0000-4000-8000-000000000001',
        'topic-generator',
        '选题生成',
        '基于账号定位、热点趋势和数据回流生成候选选题。',
        '/strategy/topics',
        'sparkles',
        'page',
        'strategy.topics',
        'topic-generation-agent',
        10,
        false,
        true,
        'planned',
        '{"phase":2}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000002',
        '10000000-0000-4000-8000-000000000002',
        'script-generator',
        '脚本生成',
        '当前可用的脚本生成、脚本列表、时间轴对照详情和状态流转闭环。',
        '/scripts/generator',
        'file-text',
        'page',
        'script.generator',
        'script-generation-agent',
        10,
        true,
        true,
        'active',
        '{"phase":1}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000003',
        '10000000-0000-4000-8000-000000000003',
        'material-search',
        '素材检索',
        '按分镜语义检索素材候选，支持标签和素材替换。',
        '/materials/search',
        'search',
        'page',
        'materials.search',
        'material-retrieval-agent',
        10,
        false,
        true,
        'planned',
        '{"phase":3}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000004',
        '10000000-0000-4000-8000-000000000004',
        'video-generation',
        '视频生成',
        '编排模板、TTS、字幕、第三方视频模型和成片任务。',
        '/production/generation',
        'film',
        'page',
        'production.generation',
        'video-generation-agent',
        10,
        false,
        true,
        'planned',
        '{"phase":4}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000005',
        '10000000-0000-4000-8000-000000000005',
        'publish-scheduler',
        '发布排程',
        '管理多平台发布时间、发布状态和失败重试。',
        '/publishing/scheduler',
        'calendar-clock',
        'page',
        'publishing.scheduler',
        'publishing-scheduler-agent',
        10,
        false,
        true,
        'planned',
        '{"phase":5}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000006',
        '10000000-0000-4000-8000-000000000006',
        'optimization-learning',
        '优化学习',
        '基于数据回流生成下一轮内容策略和优化建议。',
        '/analytics/optimization',
        'brain-circuit',
        'page',
        'analytics.optimization',
        'optimization-learning-agent',
        10,
        false,
        true,
        'planned',
        '{"phase":6}'::jsonb
    ),
    (
        '20000000-0000-4000-8000-000000000007',
        '10000000-0000-4000-8000-000000000007',
        'agent-run-monitor',
        'Agent 运行监控',
        '展示跨 Agent 任务链路、状态机、运行日志和产物流转。',
        '/workflow-tasks/runs',
        'route',
        'page',
        'workflow.runs',
        NULL,
        10,
        false,
        true,
        'planned',
        '{"phase":7}'::jsonb
    );
